apiVersion: v1
kind: Service
metadata:
  name: svc-deployment-e-replicasets-dep
spec:
  type: NodePort
  selector:
    app: app-deployment
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31306