apiVersion: v1
kind: Service
metadata:
  name: svc-deployment-canario
spec:
  type: NodePort
  selector:
    app: app-deployment-canario
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31307