apiVersion: v1
kind: Pod
metadata:
  name: backend-db-pod
  labels:
    app: backend-db-pod
spec:
  containers:
    - name: backend-db-container
      image: lucasferraz95/kubernetes-back-db-backend:1.0
      ports:
        - containerPort: 8080
      env:
        - name: DATABASE_HOST
          value: "svc-db-clusterip"
