apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
spec:
  containers:
    - name: db-container
      image: postgres:16.0-alpine3.18
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
            name: db-secret
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: db-pvc
