apiVersion: v1
kind: Service
metadata:
  name: svc-kubernetes-test-backend-clusterip
spec:
  type: NodePort
  selector:
    app: kubernetes-test-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31303