apiVersion: v1
kind: Service
metadata:
  name: svc-kubernetes-test-frontend-clusterip
spec:
  type: NodePort
  selector:
    app: kubernetes-test-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31302