version: "3.9"

services:
  postgres-db:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: local_user
      POSTGRES_DB: kubernetes_db
      POSTGRES_PASSWORD: local_password
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      - postgres-db
    environment:
      DATABASE_HOST: postgres-db

networks:
  app-network:
    driver: bridge
