apiVersion: v1
kind: Service
metadata:
  name: svc-deployment-e-replicasets-nodeport
spec:
  type: NodePort
  selector:
    app: deployment-e-replicasets-pod
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31304