apiVersion: v1
kind: Pod
metadata:
  name: app-volume-com-pvc
  labels:
    app: app-volume-com-pvc
spec:
  containers:
    - name: app-volume-com-pvc-c1
      image: lucasferraz95/kubernetes-volumes:1.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /file
          name: volume-pvc
    - name: app-volume-com-pvc-c2
      image: lucasferraz95/kubernetes-volumes:1.0
      ports:
        - containerPort: 8081
      env:
        - name: SERVER_PORT
          value: "8081"
      volumeMounts:
        - mountPath: /file
          name: volume-pvc
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: kubernetes-pvc