apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-pv
  labels:
    app: kubernetes-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/c/pv