apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-pvc
  labels:
    app: kubernetes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Mi