apiVersion: v1
kind: Service
metadata:
  name: svc-app-volume
spec:
  type: NodePort
  selector:
    app: app-volume
  ports:
    - name: c1
      port: 80
      targetPort: 8080
      nodePort: 31001
    - name: c2
      port: 5000
      targetPort: 8081
      nodePort: 31002