apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-bff
  labels:
    app: kubernetes-bff
spec:
  containers:
    - name: kubernetes-bff
      image: lucasferraz95/kubernetes-bff:1.0
      ports:
        - containerPort: 8080
      env:
        - name: API_URL
          value: "http://svc-api-clusterip"
